title: Nander Speerstra
description: The personal website of... me
theme: just-the-docs

url: https://nanderspeerstra.github.io

include:
  - _photos

aux_links:
  LinkedIn: https://nl.linkedin.com/in/nanderspeerstra
  Instagram: https://www.instagram.com/nanderspeerstra/
  Strava: https://www.strava.com/athletes/16614700
  StackOverflow: https://stackoverflow.com/users/5488275/nander-speerstra
