title: Nander Speerstra
description: The personal website of... me
theme: just-the-docs

url: https://nanderspeerstra.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
